/*
 * API Doc
 * Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;


/**
 * Model tests for DocumentRenderingBucketResponseSignedUrlsInner
 */
public class DocumentRenderingBucketResponseSignedUrlsInnerTest {
    private final DocumentRenderingBucketResponseSignedUrlsInner model = new DocumentRenderingBucketResponseSignedUrlsInner();

    /**
     * Model tests for DocumentRenderingBucketResponseSignedUrlsInner
     */
    @Test
    public void testDocumentRenderingBucketResponseSignedUrlsInner() {
        // TODO: test DocumentRenderingBucketResponseSignedUrlsInner
    }

    /**
     * Test the property 'path'
     */
    @Test
    public void pathTest() {
        // TODO: test path
    }

    /**
     * Test the property 'token'
     */
    @Test
    public void tokenTest() {
        // TODO: test token
    }

    /**
     * Test the property 'signedUrl'
     */
    @Test
    public void signedUrlTest() {
        // TODO: test signedUrl
    }

}
