/*
 * API Doc
 * Onedoc is an innovative API solution for developers, offering a simple and secure way to create and manage PDF documents using familiar technologies like React.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by Konfig (https://konfigthis.com).
 * Do not edit the class manually.
 */


package com.konfigthis.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.konfigthis.client.model.DocumentRenderingBucketResponseSignedUrlsInner;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import org.apache.commons.lang3.StringUtils;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Map.Entry;
import java.util.Set;

import com.konfigthis.client.JSON;

/**
 * DocumentRenderingBucketResponse
 */@javax.annotation.Generated(value = "Generated by https://konfigthis.com")
public class DocumentRenderingBucketResponse {
  public static final String SERIALIZED_NAME_UPLOAD_U_R_L = "uploadURL";
  @SerializedName(SERIALIZED_NAME_UPLOAD_U_R_L)
  private String uploadURL;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  private String username;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_BUCKET = "bucket";
  @SerializedName(SERIALIZED_NAME_BUCKET)
  private String bucket;

  public static final String SERIALIZED_NAME_SIGNED_URLS = "signedUrls";
  @SerializedName(SERIALIZED_NAME_SIGNED_URLS)
  private List<DocumentRenderingBucketResponseSignedUrlsInner> signedUrls = null;

  public DocumentRenderingBucketResponse() {
  }

  public DocumentRenderingBucketResponse uploadURL(String uploadURL) {
    
    
    
    
    this.uploadURL = uploadURL;
    return this;
  }

   /**
   * URL for the upload.
   * @return uploadURL
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "URL for the upload.")

  public String getUploadURL() {
    return uploadURL;
  }


  public void setUploadURL(String uploadURL) {
    
    
    
    this.uploadURL = uploadURL;
  }


  public DocumentRenderingBucketResponse username(String username) {
    
    
    
    
    this.username = username;
    return this;
  }

   /**
   * Generated username.
   * @return username
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Generated username.")

  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    
    
    
    this.username = username;
  }


  public DocumentRenderingBucketResponse password(String password) {
    
    
    
    
    this.password = password;
    return this;
  }

   /**
   * Generated password.
   * @return password
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Generated password.")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    
    
    
    this.password = password;
  }


  public DocumentRenderingBucketResponse bucket(String bucket) {
    
    
    
    
    this.bucket = bucket;
    return this;
  }

   /**
   * Identifier of the bucket.
   * @return bucket
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "Identifier of the bucket.")

  public String getBucket() {
    return bucket;
  }


  public void setBucket(String bucket) {
    
    
    
    this.bucket = bucket;
  }


  public DocumentRenderingBucketResponse signedUrls(List<DocumentRenderingBucketResponseSignedUrlsInner> signedUrls) {
    
    
    
    
    this.signedUrls = signedUrls;
    return this;
  }

  public DocumentRenderingBucketResponse addSignedUrlsItem(DocumentRenderingBucketResponseSignedUrlsInner signedUrlsItem) {
    if (this.signedUrls == null) {
      this.signedUrls = new ArrayList<>();
    }
    this.signedUrls.add(signedUrlsItem);
    return this;
  }

   /**
   * Get signedUrls
   * @return signedUrls
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<DocumentRenderingBucketResponseSignedUrlsInner> getSignedUrls() {
    return signedUrls;
  }


  public void setSignedUrls(List<DocumentRenderingBucketResponseSignedUrlsInner> signedUrls) {
    
    
    
    this.signedUrls = signedUrls;
  }

  /**
   * A container for additional, undeclared properties.
   * This is a holder for any undeclared properties as specified with
   * the 'additionalProperties' keyword in the OAS document.
   */
  private Map<String, Object> additionalProperties;

  /**
   * Set the additional (undeclared) property with the specified name and value.
   * If the property does not already exist, create it otherwise replace it.
   *
   * @param key name of the property
   * @param value value of the property
   * @return the DocumentRenderingBucketResponse instance itself
   */
  public DocumentRenderingBucketResponse putAdditionalProperty(String key, Object value) {
    if (this.additionalProperties == null) {
        this.additionalProperties = new HashMap<String, Object>();
    }
    this.additionalProperties.put(key, value);
    return this;
  }

  /**
   * Return the additional (undeclared) property.
   *
   * @return a map of objects
   */
  public Map<String, Object> getAdditionalProperties() {
    return additionalProperties;
  }

  /**
   * Return the additional (undeclared) property with the specified name.
   *
   * @param key name of the property
   * @return an object
   */
  public Object getAdditionalProperty(String key) {
    if (this.additionalProperties == null) {
        return null;
    }
    return this.additionalProperties.get(key);
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentRenderingBucketResponse documentRenderingBucketResponse = (DocumentRenderingBucketResponse) o;
    return Objects.equals(this.uploadURL, documentRenderingBucketResponse.uploadURL) &&
        Objects.equals(this.username, documentRenderingBucketResponse.username) &&
        Objects.equals(this.password, documentRenderingBucketResponse.password) &&
        Objects.equals(this.bucket, documentRenderingBucketResponse.bucket) &&
        Objects.equals(this.signedUrls, documentRenderingBucketResponse.signedUrls)&&
        Objects.equals(this.additionalProperties, documentRenderingBucketResponse.additionalProperties);
  }

  @Override
  public int hashCode() {
    return Objects.hash(uploadURL, username, password, bucket, signedUrls, additionalProperties);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentRenderingBucketResponse {\n");
    sb.append("    uploadURL: ").append(toIndentedString(uploadURL)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    bucket: ").append(toIndentedString(bucket)).append("\n");
    sb.append("    signedUrls: ").append(toIndentedString(signedUrls)).append("\n");
    sb.append("    additionalProperties: ").append(toIndentedString(additionalProperties)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("uploadURL");
    openapiFields.add("username");
    openapiFields.add("password");
    openapiFields.add("bucket");
    openapiFields.add("signedUrls");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Object and throws an exception if issues found
  *
  * @param jsonObj JSON Object
  * @throws IOException if the JSON Object is invalid with respect to DocumentRenderingBucketResponse
  */
  public static void validateJsonObject(JsonObject jsonObj) throws IOException {
      if (jsonObj == null) {
        if (!DocumentRenderingBucketResponse.openapiRequiredFields.isEmpty()) { // has required fields but JSON object is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in DocumentRenderingBucketResponse is not found in the empty JSON string", DocumentRenderingBucketResponse.openapiRequiredFields.toString()));
        }
      }
      if ((jsonObj.get("uploadURL") != null && !jsonObj.get("uploadURL").isJsonNull()) && !jsonObj.get("uploadURL").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `uploadURL` to be a primitive type in the JSON string but got `%s`", jsonObj.get("uploadURL").toString()));
      }
      if ((jsonObj.get("username") != null && !jsonObj.get("username").isJsonNull()) && !jsonObj.get("username").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `username` to be a primitive type in the JSON string but got `%s`", jsonObj.get("username").toString()));
      }
      if ((jsonObj.get("password") != null && !jsonObj.get("password").isJsonNull()) && !jsonObj.get("password").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `password` to be a primitive type in the JSON string but got `%s`", jsonObj.get("password").toString()));
      }
      if ((jsonObj.get("bucket") != null && !jsonObj.get("bucket").isJsonNull()) && !jsonObj.get("bucket").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `bucket` to be a primitive type in the JSON string but got `%s`", jsonObj.get("bucket").toString()));
      }
      if (jsonObj.get("signedUrls") != null && !jsonObj.get("signedUrls").isJsonNull()) {
        JsonArray jsonArraysignedUrls = jsonObj.getAsJsonArray("signedUrls");
        if (jsonArraysignedUrls != null) {
          // ensure the json data is an array
          if (!jsonObj.get("signedUrls").isJsonArray()) {
            throw new IllegalArgumentException(String.format("Expected the field `signedUrls` to be an array in the JSON string but got `%s`", jsonObj.get("signedUrls").toString()));
          }

          // validate the optional field `signedUrls` (array)
          for (int i = 0; i < jsonArraysignedUrls.size(); i++) {
            DocumentRenderingBucketResponseSignedUrlsInner.validateJsonObject(jsonArraysignedUrls.get(i).getAsJsonObject());
          };
        }
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!DocumentRenderingBucketResponse.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'DocumentRenderingBucketResponse' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<DocumentRenderingBucketResponse> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(DocumentRenderingBucketResponse.class));

       return (TypeAdapter<T>) new TypeAdapter<DocumentRenderingBucketResponse>() {
           @Override
           public void write(JsonWriter out, DocumentRenderingBucketResponse value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             obj.remove("additionalProperties");
             // serialize additonal properties
             if (value.getAdditionalProperties() != null) {
               for (Map.Entry<String, Object> entry : value.getAdditionalProperties().entrySet()) {
                 if (entry.getValue() instanceof String)
                   obj.addProperty(entry.getKey(), (String) entry.getValue());
                 else if (entry.getValue() instanceof Number)
                   obj.addProperty(entry.getKey(), (Number) entry.getValue());
                 else if (entry.getValue() instanceof Boolean)
                   obj.addProperty(entry.getKey(), (Boolean) entry.getValue());
                 else if (entry.getValue() instanceof Character)
                   obj.addProperty(entry.getKey(), (Character) entry.getValue());
                 else {
                   obj.add(entry.getKey(), gson.toJsonTree(entry.getValue()).getAsJsonObject());
                 }
               }
             }
             elementAdapter.write(out, obj);
           }

           @Override
           public DocumentRenderingBucketResponse read(JsonReader in) throws IOException {
             JsonObject jsonObj = elementAdapter.read(in).getAsJsonObject();
             validateJsonObject(jsonObj);
             // store additional fields in the deserialized instance
             DocumentRenderingBucketResponse instance = thisAdapter.fromJsonTree(jsonObj);
             for (Map.Entry<String, JsonElement> entry : jsonObj.entrySet()) {
               if (!openapiFields.contains(entry.getKey())) {
                 if (entry.getValue().isJsonPrimitive()) { // primitive type
                   if (entry.getValue().getAsJsonPrimitive().isString())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsString());
                   else if (entry.getValue().getAsJsonPrimitive().isNumber())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsNumber());
                   else if (entry.getValue().getAsJsonPrimitive().isBoolean())
                     instance.putAdditionalProperty(entry.getKey(), entry.getValue().getAsBoolean());
                   else
                     throw new IllegalArgumentException(String.format("The field `%s` has unknown primitive type. Value: %s", entry.getKey(), entry.getValue().toString()));
                 } else if (entry.getValue().isJsonArray()) {
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), List.class));
                 } else { // JSON object
                     instance.putAdditionalProperty(entry.getKey(), gson.fromJson(entry.getValue(), HashMap.class));
                 }
               }
             }
             return instance;
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of DocumentRenderingBucketResponse given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of DocumentRenderingBucketResponse
  * @throws IOException if the JSON string is invalid with respect to DocumentRenderingBucketResponse
  */
  public static DocumentRenderingBucketResponse fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, DocumentRenderingBucketResponse.class);
  }

 /**
  * Convert an instance of DocumentRenderingBucketResponse to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

